### ISSUE TITLE
CHECKLIST PENDIENTES

### ISSUE THREAD

**Issue by Adrincovich** [ojedamilton/suf#53]
ADRIAN:

- [x] Diagramas de casos de uso
- [x] Diagramas de robustez
- [x] Bosquejos de interfaz a mano
- [x] Diagrama de despliegue

MILTON:
- [x] #54
- [x] Revisión general de codigo
